"""Normalized data model for PatchTriage.

Every scanner output (Trivy, Grype, OSV, ...) is mapped into `RawFinding`.
Dedup merges RawFindings into `Finding` (one per CVE x package x asset).
Enrichment attaches authoritative signals (EPSS / KEV / NVD and vendor
advisories) — these values are ALWAYS fetched deterministically, never
generated by an LLM.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


_ASSET_SSVC_CHOICES = {
    "system_exposure": {"small", "controlled", "open", "unknown"},
    "automatable": {"yes", "no", "unknown"},
    "mission_impact": {
        "degraded", "mef_support_crippled", "mef_failure",
        "mission_failure", "unknown",
    },
    "safety_impact": {
        "negligible", "marginal", "critical", "catastrophic", "unknown",
    },
}


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    NEGLIGIBLE = "negligible"
    UNKNOWN = "unknown"

    @classmethod
    def parse(cls, value: str | None) -> "Severity":
        if not value:
            return cls.UNKNOWN
        v = value.strip().lower()
        aliases = {"moderate": "medium", "important": "high", "negligible": "negligible"}
        v = aliases.get(v, v)
        try:
            return cls(v)
        except ValueError:
            return cls.UNKNOWN


class Package(BaseModel):
    """The vulnerable component."""

    name: str
    version: str = ""
    ecosystem: str = ""          # e.g. debian, alpine, npm, pypi, golang
    purl: str = ""               # package URL if the scanner provides one
    fixed_version: str = ""      # earliest version that fixes the vuln ("" = no fix yet)


class Asset(BaseModel):
    """Where the vulnerable component lives."""

    identifier: str              # hostname, image ref, repo path, ...
    kind: str = "unknown"        # host | container_image | repository | ...
    criticality: str = "unknown" # business criticality: critical|high|medium|low|unknown
    internet_exposed: Optional[bool] = None
    reachable: Optional[bool] = None         # vulnerable code path is statically reachable
    runtime_observed: Optional[bool] = None  # component/path observed by eBPF/Falco/OTel
    # SSVC Deployer context. "unknown" invokes the documented conservative
    # default and is surfaced for user confirmation rather than hidden.
    system_exposure: str = "unknown"        # small|controlled|open|unknown
    automatable: str = "unknown"            # yes|no|unknown
    mission_impact: str = "unknown"         # degraded|mef_support_crippled|mef_failure|mission_failure|unknown
    safety_impact: str = "unknown"          # negligible|marginal|critical|catastrophic|unknown
    context_sources: list[str] = Field(default_factory=list)
    owner: str = ""
    context_notes: str = ""

    @field_validator(*_ASSET_SSVC_CHOICES, mode="before")
    @classmethod
    def validate_ssvc_context(cls, value, info):
        if info.field_name == "automatable" and isinstance(value, bool):
            return "yes" if value else "no"
        normalized = str(value or "unknown").strip().lower().replace("-", "_")
        if normalized not in _ASSET_SSVC_CHOICES[info.field_name]:
            allowed = ", ".join(sorted(_ASSET_SSVC_CHOICES[info.field_name]))
            raise ValueError(f"{info.field_name} must be one of: {allowed}")
        return normalized


class RawFinding(BaseModel):
    """One vulnerability record exactly as one scanner reported it."""

    vuln_id: str                          # canonical id, prefer CVE-*
    aliases: list[str] = Field(default_factory=list)
    source_scanner: str                   # trivy | grype | osv | nessus | ...
    package: Package
    asset: Asset
    severity: Severity = Severity.UNKNOWN
    cvss_score: Optional[float] = None    # scanner-reported CVSS (may differ from NVD)
    title: str = ""
    description: str = ""
    references: list[str] = Field(default_factory=list)
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    raw: dict = Field(default_factory=dict, exclude=True)  # original record for audit


class VendorAdvisory(BaseModel):
    """A normalized record from an authoritative vendor advisory feed."""

    source: str                         # msrc | rhsa | usn | debian | ghsa
    advisory_id: str
    title: str = ""
    url: str = ""
    severity: str = ""
    published_at: str = ""
    products: list[str] = Field(default_factory=list)
    fixed_versions: list[str] = Field(default_factory=list)
    vulnerable_functions: list[str] = Field(default_factory=list)


class Enrichment(BaseModel):
    """Authoritative, deterministic signals. Never LLM-generated."""

    epss_score: Optional[float] = None        # probability of exploitation (FIRST EPSS)
    epss_percentile: Optional[float] = None
    in_cisa_kev: bool = False                 # known exploited in the wild
    kev_ransomware: bool = False              # KEV flags ransomware campaign use
    kev_due_date: Optional[str] = None
    nvd_cvss_score: Optional[float] = None
    nvd_cvss_vector: str = ""
    nvd_cvss_version: str = ""
    cwe_ids: list[str] = Field(default_factory=list)
    exploit_references: list[str] = Field(default_factory=list)
    vendor_advisories: list[VendorAdvisory] = Field(default_factory=list)
    vendor_sources_checked: list[str] = Field(default_factory=list)
    vendor_lookup_errors: list[str] = Field(default_factory=list)
    enriched_at: Optional[datetime] = None
    sources: list[str] = Field(default_factory=list)


class Finding(BaseModel):
    """Deduplicated finding: one per (vuln_id, package.name, asset.identifier).

    `reported_by` keeps track of every scanner that saw it, so nothing is lost.
    """

    key: str                                  # stable dedup key
    vuln_id: str
    aliases: list[str] = Field(default_factory=list)
    package: Package
    asset: Asset
    severity: Severity = Severity.UNKNOWN     # max severity across scanners
    cvss_score: Optional[float] = None        # max scanner CVSS
    title: str = ""
    description: str = ""
    references: list[str] = Field(default_factory=list)
    reported_by: list[str] = Field(default_factory=list)
    first_seen: Optional[datetime] = None
    enrichment: Enrichment = Field(default_factory=Enrichment)

    # Filled by Layer 5 (AI triage) — clearly separated from ground truth above.
    triage: Optional[dict] = None
